module.exports = {
    crew_page:[
        "ID=crewPartnerModal",
        "CLASS=style_showContainer_kSC",
        "CLASS=style_container_frs",
        "XPATH=//*[@id='crewPartnerModal']/div/div/div/div[2]/div[1]/div[4]",
    ],
    se_connecter:[
        "CLASS=style_whiteButton_4el",
        "XPATH=//*[@id='crewPartnerModal']/div/div/div/div[2]/div[2]/div/div[1]/button"
    ],
    s_inscrire:[
        "CLASS=style_redButton_+LW",
        "XPATH=//*[@id='crewPartnerModal']/div/div/div/div[2]/div[2]/div/div[2]/button",
    ],
    close:[
        "CLASS=style_closeIcon_eF8",
        "XPATH=//*[@id='crewPartnerModal']/div/div/div/div[2]/a",
    ],
    activer_remboursement:[
        "CLASS=style_redButton_+LW",
        "XPATH=//*[@id='crewPartnerModal']/div/div/div/div[2]/div[2]/div/button",
    ],
    vous_avez_fait_votre_achat:[
        "CLASS=style_crewPartnerSuccessModalTitle_e6l",
        "XPATH=//*[@id='crewPartnerModal']/div/div/div/div[2]/div[1]/div/h1",
    ],
    une_question:[
        "CLASS=style_whiteButton_4el",
        "XPATH=//*[@id='crewPartnerModal']/div/div/div/div[2]/div[2]/div/div[1]/button",
    ],
}