module.exports = {
    login_page:[
        "ID=content",
        "SELECTOR=#content",
        "XPATH=//*[@id='content']"
    ],
    login_page_header:[
        "CLASS=Hea1",
        "ID=header",
    ],
    login_email:[
        "NAME=j_username",
    ],
    login_password:[
        "NAME=j_password",
    ],
    me_connecter:[
        "NAME=submitLogin",
        "XPATH=//*[@id='content']/section[1]/form/div/div[2]/span/span"
    ],
    continuer:[
        "SELECTOR=#content > section.newUser > div > a > div > button",
        "XPATH=//*[@id='content']/section[2]/div/a/div/button]"
    ],
    signup_email:[
        "ID=userEmail",
        "SELECTOR=#userEmail",
        "XPATH=//*[@id='userEmail']"
    ],
    signup_email_confirm:[
        "ID=e_mail2",
        "SELECTOR=#e_mail2",
        "XPATH=//*[@id='e_mail2']"
    ],
    signup_password:[
        "ID=userPassword",
        "SELECTOR=#userPassword",
        "XPATH=//*[@id='userPassword']"
    ],
    mrs_gender:[
        "CLASS=ui-icon ui-icon-radio-off ui-icon-shadow",
        "LEVEL=0",
    ],
    mr_gender:[
        "CLASS=ui-icon ui-icon-radio-off ui-icon-shadow",
        "LEVEL=1",
    ],
    first_name:[
        "ID=userFirstName",
        "SELECTOR=#userFirstName",
        "XPATH=//*[@id='userFirstName']"
    ],
    last_name:[
        "ID=userLastName",
        "SELECTOR=#userLastName",
        "XPATH=//*[@id='userLastName']"
    ],
    day_of_birth:[
        "ID=birthDay",
        "SELECTOR=#birthDay",
        "XPATH=//*[@id='birthDay']"
    ],
    month_of_birth:[
        "ID=birthMonth",
        "SELECTOR=#birthMonth",
        "XPATH=//*[@id='birthMonth']"
    ],
    year_of_birth:[
        "ID=birthYear",
        "SELECTOR=#birthYear",
        "XPATH=//*[@id='birthYear']"
    ],
    creer_compte:[
        "ID=submitSubscription",
        "SELECTOR=#submitSubscription",
        "XPATH=//*[@id='submitSubscription']"
    ],
    bad_credentials:[
        "ID=migrationErrorNotif",
        "SELECTOR=#migrationErrorNotif",
        "XPATH=//*[@id='migrationErrorNotif']"
    ],
}