module.exports = {
    _body:[
        "ID=main",
    ],
    _header:[
        "ID=panel_head",
    ],
    _card_number:[
        "XPATH=//div[@data-processout-input='cc-number']//iframe",
    ],
    _card_expiration_date:[
        "XPATH=//div[@data-processout-input='cc-exp']//iframe",
    ],
    _card_secret:[
        "XPATH=//div[@data-processout-input='cc-cvc']//iframe",
    ],
    _klarna:[
        "ID=gway_conf_vz5q34opggjy00n6tz4zvdtxnehh1mt3.klarna"
    ],
    _oney4x:[
        "ID=gway_conf_4l4dq3zj023sx63zkoesn8xfjy50fwbk.oney",
    ],
    _oney8x:[
        "ID=gway_conf_4s6v2djjygicw0vm0t9bc06ex1j01ha3.oney",
    ],
    _oney12x:[
        "ID=gway_conf_dmwm1khttgq1g4bmcb64dimna9yo4yrv.oney",
    ],
    _paypal:[
        "ID=gway_conf_1cl3vhwaz50hpyr5x3gdkt2fa3gwq27a.paypalexpresscheckout"
    ],
    _processout:[
        "ID=gway_conf_b07cbe7e185b82193719838d219eb2dd.sandbox",
    ],
    _processout_accept:[
        "ID=sandbox-token-test-valid"
    ],
    _valider_payment:[
        "ID=checkout_submit_btn"
    ],
    _success_payment:[
        "CLASS=rp-adunit__image",
        "ID=sandbox-token-test-valid"
    ]
}