module.exports = {
    _body:[
        "ID=location",
        "SELECTOR=#location",
        "XPATH=//*[@id='location']"
    ],
    _header:[
        "CLASS=Hea1",
    ],
    _login_email:[
        "ID=auth_user_identifier",
        "SELECTOR=#auth_user_identifier",
        "XPATH=//*[@id='auth_user_identifier']"
    ],
    _login_password:[
        "ID=userpassword",
        "SELECTOR=#userpassword",
        "XPATH=//*[@id='userpassword']"
    ],
    _me_connecter:[
        "ID=sbtn_login",
        "SELECTOR=#sbtn_login",
        "XPATH=//*[@id='sbtn_login']"
    ],
    _continuer:[
        "ID=sbtn_register",
        "SELECTOR=#sbtn_register",
        "XPATH=//*[@id='sbtn_register']"
    ],
    _signup_email:[
        "ID=e_mail",
        "SELECTOR=#e_mail",
        "XPATH=//*[@id='e_mail']"
    ],
    _signup_email_confirm:[
        "ID=e_mail2",
        "SELECTOR=#e_mail2",
        "XPATH=//*[@id='e_mail2']"
    ],
    _signup_password:[
        "ID=password",
        "SELECTOR=#password",
        "XPATH=//*[@id='password']"
    ],
    _mrs_gender:[
        "ID=radio_1",
    ],
    _mr_gender:[
        "ID=radio_2",
    ],
    _first_name:[
        "ID=first_name",
        "SELECTOR=#first_name",
        "XPATH=//*[@id='first_name']"
    ],
    _last_name:[
        "ID=last_name",
        "SELECTOR=#last_name",
        "XPATH=//*[@id='last_name']"
    ],
    _day_of_birth:[
        "ID=birth_day",
        "SELECTOR=#birth_day",
        "XPATH=//*[@id='birth_day']"
    ],
    _month_of_birth:[
        "ID=birth_month",
        "SELECTOR=#birth_month",
        "XPATH=//*[@id='birth_month']"
    ],
    _year_of_birth:[
        "ID=birth_year",
        "SELECTOR=#birth_year",
        "XPATH=//*[@id='birth_year']"
    ],
    _creer_compte:[
        "ID=submit_btn2"
    ],
    _bad_credentials:[
        "ID=leadCol",
        "SELECTOR=#leadCol",
        "XPATH=//*[@id='leadCol']"
    ],
}