module.exports = {
    _body:[
        "ID=content",
        "SELECTOR=#content",
        "XPATH=//*[@id='content']"
    ],
    _header:[
        "CLASS=Hea1",
    ],
    _login_email:[
        "NAME=j_username",
    ],
    _login_password:[
        "NAME=j_password",
    ],
    _me_connecter:[
        "NAME=submitLogin",
        "XPATH=//*[@id='content']/section[1]/form/div/div[2]/span/span"
    ],
    _continuer:[
        "SELECTOR=#content > section.newUser > div > a > div > button",
        "XPATH=//*[@id='content']/section[2]/div/a/div/button]"
    ],
    _signup_email:[
        "ID=userEmail",
        "SELECTOR=#userEmail",
        "XPATH=//*[@id='userEmail']"
    ],
    _signup_email_confirm:[
        "ID=e_mail2",
        "SELECTOR=#e_mail2",
        "XPATH=//*[@id='e_mail2']"
    ],
    _signup_password:[
        "ID=userPassword",
        "SELECTOR=#userPassword",
        "XPATH=//*[@id='userPassword']"
    ],
    _mrs_gender:[
        "CLASS=fld_lbl",
        "XPATH=//*[@id='frm_subscription']/fieldset[1]/div[4]/div[1]/div/label/span/span[2]",
    ],
    _mr_gender:[
        "CLASS=fld_lbl",
        "XPATH=//*[@id='frm_subscription']/fieldset[1]/div[4]/div[2]/div/label/span/span[2]",
    ],
    _first_name:[
        "ID=userFirstName",
        "SELECTOR=#userFirstName",
        "XPATH=//*[@id='userFirstName']"
    ],
    _last_name:[
        "ID=userLastName",
        "SELECTOR=#userLastName",
        "XPATH=//*[@id='userLastName']"
    ],
    _day_of_birth:[
        "ID=birthDay",
        "SELECTOR=#birthDay",
        "XPATH=//*[@id='birthDay']"
    ],
    _month_of_birth:[
        "ID=birthMonth",
        "SELECTOR=#birthMonth",
        "XPATH=//*[@id='birthMonth']"
    ],
    _year_of_birth:[
        "ID=birthYear",
        "SELECTOR=#birthYear",
        "XPATH=//*[@id='birthYear']"
    ],
    _creer_compte:[
        "ID=submitSubscription",
        "SELECTOR=#submitSubscription",
        "XPATH=//*[@id='submitSubscription']"
    ],
    _bad_credentials:[
        "ID=migrationErrorNotif",
        "SELECTOR=#migrationErrorNotif",
        "XPATH=//*[@id='migrationErrorNotif']"
    ],
}